version: "3.5"
services:
  geth:
    build:
      context: op-geth
      args:
        UPSTREAM_VERSION: v1.101105.3
    volumes:
      - "data:/data"
    ports:
      - "33141:33141/tcp"
      - "33141:33141/udp"
    restart: unless-stopped
    environment:
      - EXTRA_FLAGS
      - P2P_PORT=33141
      - SYNCMODE=snap
volumes:
  data: {}
