version: "3.5"
services:
  l2geth:
    build:
      context: l2geth
      args:
        UPSTREAM_VERSION: 0.5.31
    volumes:
      - "data:/data"
    restart: unless-stopped
    environment:
      - EXTRA_FLAGS
    image: "l2geth.op-l2geth.dnp.dappnode.eth:0.1.0"
volumes:
  data: {}
